package generation.biomes;

public enum BIOME {
	RIVER,OCEAN,TROP_RAINFOREST,TROP_SEASONAL,GRASSLAND,DESERT,
	TEMP_RAINFOREST,TEMP_DECIDUOUS,TEMP_DESERT,
	TAIGIA,SHRUBLAND,
	SNOW,TUNDRA,BARE,SCORCHED
}
